plugins:
  ghostmode_enabled:
    default: true
    client: true
  ghostmode_topics:
    default: ""
    client: false
  ghostmode_posts:
    default: ""
    client: false
  ghostmode_show_to_staff:
    default: false
    client: true
